version: 2
jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: Check codestandards
          command: ./vendor/bin/phing check-codestandards
      - run:
          name: Static analysis
          command: ./vendor/bin/phing phpstan
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
