version: 2
jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "composer.lock" }}
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: Check codestandards
          command: ./bin/phing check-codestandards
      - run:
          name: Static analysis
          command: ./bin/phing phpstan
      - save_cache:
          key: cache-{{ checksum "composer.lock" }}
          paths:
            - /var/www/vendor
            - /var/www/bin

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
