version: 2
jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.0
    workDir: /var/www
    steps:
      - checkout
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
          
      - restore_cache:
          key: cache-v10-{{ checksum "composer.lock" }}

      - run:
          name: Composer install
          command: composer install --prefer-dist --no-interaction
          
      - save_cache:
          key: cache-v10-{{ checksum "composer.lock" }}
          paths:
            - /var/www/vendor
      - run:
          name: Check codestandards
          command: ./vendor/bin/phing check-codestandards
      - run:
          name: Static analysis
          command: ./vendor/bin/phing phpstan

  deprecations_check:
    docker:
      - image: msvrtan/square:0.2.2
    working_directory: /var/www
    parallel: 1
    steps:
      - checkout

      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh

      - run:
          name: Composer install
          command: composer install --prefer-dist --no-interaction

      - run:
          name: Add phpstan deprecation rules
          command: sed -i.bak $'s/includes:/includes:\\\n\t- vendor\/phpstan\/phpstan-deprecation-rules\/rules.neon/g' phpstan.neon

      - run:
          name: PHPStan
          command: ./vendor/bin/phing phpstan

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deprecations_check:
         requires:
           - build